USE PROYECTO_INR;

DROP PROCEDURE IF EXISTS SP_VALIDAUSUARIO;
DELIMITER $$
CREATE PROCEDURE SP_VALIDAUSUARIO(usu varchar(45),pass varchar(45))
BEGIN
	SELECT * FROM EMPLEADO 
    WHERE usuario=usu and psswrd=pass;
END$$ 
DELIMITER ;

